export const actionTypes = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  REGISTER: "REGISTER",
  VERIFY: "VERIFY",
  CHANGEPASSWORD: "CHANGEPASSWORD",
  TO_LOGIN: "TO_LOGIN",
  TO_REGISTER: "TO_REGISTER",
  TO_VERIFY: "TO_VERIFY"
};
