language: node_js
node_js:
  - 11

addons:
  sonarcloud:
    organization: "jsulpis-github"
    token: $SONAR_TOKEN

cache: yarn

script:
  - yarn lint
  - yarn test:coverage
  - yarn build
  - sonar-scanner

branches:
  only:
    - master
